apiVersion: v1
kind: Pod
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  containers:
  - name: sonarqube
    image: sonarqube
    ports:
      - containerPort: 9000

--- 

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
  - port: 80
    targetPort: 9000
