apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-label
  template:
    metadata:
      labels:
        app: get-label
    spec:
      containers:
      - name: get-con
        image: appacrakash01.azurecr.io/todo-get-tasks-api:v1   
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sqlserverakash01.database.windows.net,1433;Database=sql_db;Uid=sql_username;Pwd=Password@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
          