apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      containers:
      - name: get-tasks
        env:
          - name: FRUITNAME
            valueFrom:
              configMapKeyRef:
                key: 
                name:                                            
        image: devopsinsiders/get-tasks
        ports:
        - containerPort: 8000
