apiVersion: v1
kind: Secret
metadata:
  name: dbdetails
type: Opaque
data:
  kchbhi: RHJpdmVyPXtPREJDIERyaXZlciAxNyBmb3IgU1FMIFNlcnZlcn07U2VydmVyPXRjcDpha3MtZGIuZGF0YWJhc2Uud2luZG93cy5uZXQsMTQzMztEYXRhYmFzZT10b2RvYXBwREI7VWlkPWRldm9wc2luc2lkZXI7UHdkPXNoaXZlc2hAMTIzNDtFbmNyeXB0PXllcztUcnVzdFNlcnZlckNlcnRpZmljYXRlPW5vO0Nvbm5lY3Rpb24gVGltZW91dD0zMA==
  